### PR TITLE
Improved Home Assistant support + bugfix from @helmut8960

### PR DESCRIPTION
**Pull request by Tropaion**
Hello,

added better functionality for HomeAssistant.
Entities are now grouped into devices according to their group name set in p4d:
image

### CODE REVIEW

**Comment by hoppel118** [comment]
This is really cool! @horchi I need this! 😃

**Comment by yesfirst13** [comment]
@Tropaion Maybe it helps @horchi if you rebase to resolve the conflicts. 
I would also see this as a great improvement ;-)

**Comment by Tropaion** [comment]
@yesfirst13 The base is not the problem, it's only about the history. We just have to wait for @horchi to be active again.

**Comment by horchi** [comment]
I have manually adapted the patch slightly. Hope no error has crept in

**Comment by hoppel118** [comment]
Hi, great that we have some progress here. Very nice! I can't wait to get this running.

@horchi When will we get a new version for raspberry pis?

At the moment I only get version 0.9.47. But this doesn't seem to include this very welcome contribution.

@Tropaion Do I need to configure something special on my HA or p4d?

I have my groups already configured from the time when I used FHEM:

screenshot_1900

My IO setup looks as follows for example:

screenshot_1901

With the migration from FHEM to HA, I configured my HA the following way, because groups didn't work:

screenshot_1898

IMO I need to change this as follows, if I understand your opening post right?

screenshot_1899

Will I loose all my data in HA or what will happen with the already existing entities?

Thanks you so much @Tropaion and @horchi

**Comment by Tropaion** [comment]
@hoppel118 You don't need any additional configuration, it should work with the default HA setup:
image
Mine looks like this. But I haven't tested horchis version yet, only my fork.
Your current entites will probably dissappear and new ones will be created, but I can't say for sure, since I tested it with a new installation.

**Comment by hoppel118** [comment]
@Tropaion Ok, let me try that, when hochi launched his new version. Should <GROUP> work, too?

**Comment by Tropaion** [comment]
@hoppel118 Group should work, but I'm not sure, haven't tried it, I only made simple changes :D

**Comment by hoppel118** [comment]
Hi @Tropaion and @horchi,

happ new year. Thanks again for the latest changes. I have it working now. I see one device with 45 entities. p4d is configured as follows:

screenshot_1904

in Home Assistant I see the following:

screenshot_1905

screenshot_1908

So far so good. With MQTT Explorer I recognized that there are two p4d topics.

screenshot_1911

screenshot_1913

screenshot_1912

I assume that Home Assistant uses the "homeassistant" topic only, and not the "p4d2mqtt", because homeassistant topic has 45 subtopics. The device in Home Assistant also has 45 entities.

When I configure GROUP instead of NAME:

screenshot_1914

I see the following in the MQTT Explorer:

screenshot_1915

The topic "p4d2mqtt" is there and and I see my GROUPs (Baugruppen), but I miss my subtopics / entities in Home Assistant. The "homeassistant" topic is not created, when I use GROUP.

No big drama, I use the NAME variant at the moment. I didn't use GROUPs since I migrated from FHEM to HA, because I didn't get it to work.

Any idea, what is wrong?

Cheers Hoppel

**Comment by Tropaion** [comment]
@hoppel118 Looks like you have some progress.
For your issue you should write a new issue since @horchi knows more about his software and it looks like he didn't apply all my changes (I think).

**Comment by horchi** [comment]
ja der Home Assistant benötigt das "homeassistant" Topic zur Konfiguration der Sensoren - daran erinnere ich mich noch. 

Dieses 'config' Topic wird nur geschrieben wenn im Topic-Name Template <NAME> verwendet wird, das war schon immer so implementiert und hat sich auch mit dem Patch - wenn ich  nichts übersehe - nicht geändert.
Oder @Tropaion sollte der Patch da etwas anpassen das ich vergessen habe?

Ich habe selbst keinen Home Assistant und kann es nicht testen

**Comment by hoppel118** [comment]
> For your issue you should write a new issue since @horchi knows more about his software and it looks like he didn't apply all my changes (I think).

OK, here we go: https://github.com/horchi/linux-p4d/issues/47

Thanks and regards Hoppel

**Pull request closed without merging**
